services:
  # docker compose exec db-postgres bash
  db-postgres:
    image: postgres:17.4
    container_name: db-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    volumes:
      - db-pg-data:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  # docker compose exec db-mysql bash
  db-mysql:
    #image: mysql:9.3.0
    image: mysql:8.4.4
    container_name: db-mysql
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-mysql-data:/var/lib/mysql
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql//docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db-mysql-data:
  db-pg-data:
